apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags-pv
spec:
  storageClassName: nfs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /home/${USER}/Investment-Project/src/airflow/dags
    server: ${SERVER_IP}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: airflow-dags-pv  # 사용할 PV 이름

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs-pv
spec:
  storageClassName: nfs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /home/${USER}/Investment-Project/src/airflow/logs
    server: ${SERVER_IP}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: airflow-logs-pv  # 사용할 PV 이름

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-data-pv
spec:
  storageClassName: nfs
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /home/${USER}/Investment-Project/src/airflow/data
    server: ${SERVER_IP}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-data-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: airflow-data-pv  # 사용할 PV 이름

