apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
spec:
  storageClassName: nfs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /home/dongwook.test9/Investment-Project/src/minio
    server: ${SERVER_IP}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: minio-pv  # 사용할 PV 이름

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio
          args:
            - server
            - /data
            - --console-address
            - ":9090"
          ports:
            - containerPort: 9000
            - containerPort: 9090
          volumeMounts:
            - name: minio-pv
              mountPath: /data
          env:
            - name: MINIO_ACCESS_KEY
              value: test_access_key
            - name: MINIO_SECRET_KEY
              value: test_secret_key
            - name: MINIO_ROOT_USER
              value: test_user_id
            - name: MINIO_ROOT_PASSWORD
              value: test_user_password
      volumes:
        - name: minio-pv
          persistentVolumeClaim:
            claimName: minio-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - name: http
      port: 9000
      targetPort: 9000
    - name: http-service
      port: 9090
      targetPort: 9090
      nodePort: 30082
