FROM python:3.8

USER root

COPY main.py main.py
COPY requirements.txt requirements.txt

RUN apt-get update && pip3 install -r requirements.txt

CMD ["python", "main.py", "--ticker", "KRW-BTC", "KRW-ETH"]
