# ticker pod
apiVersion: v1
kind: Pod
metadata:
  name: ticker
spec:
  containers:
  - name: ticker
    image: ehddnr/ticker:1.1.0
    imagePullPolicy: Always
    volumeMounts:
    - name: logs-volume
      mountPath: /logs
  - name: fluentd
    image: ehddnr/fluentd:1.1.0
    imagePullPolicy: Always
    volumeMounts:
    - name: logs-volume
      mountPath: /logs
    - name: config
      mountPath: /fluentd/etc/fluent.conf
      subPath: fluent.conf  
  volumes:
  - name: logs-volume
    emptyDir: {}
  - name: config
    configMap:
      name: fluentd-config  