# minio.yaml의 첫번재 오브젝트
# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
spec:
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit
        image: ehddnr/streamlit:1.0.0
        imagePullPolicy: Always
        command: ["streamlit", "run", "project/app.py"]
        ports:
        - name: http
          containerPort: 8501
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  type: NodePort
  selector:
    app: streamlit
  ports:
    - name: http
      port: 8501
      targetPort: 8501
      nodePort: 30085
