- hosts: all
  become: yes
  tasks:
    - name: create the '{{ ansible_user }}' user
      user: name={{ ansible_user }} append=yes state=present createhome=yes shell=/bin/bash
 
    - name: allow '{{ ansible_user }}' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: '{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Clone a github repository
      git:
        repo: '{{ repo_url }}'
        dest: '/home/{{ ansible_user }}//Investment-Project'
        clone: yes
        update: yes
      become_user: '{{ ansible_user }}'

    - name: Creates Minio Bucket directory
      file:
        path: '/home/{{ ansible_user }}//Investment-Project/src/minio/test'
        state: directory

    - name: Set Minio directory permissions
      file:
        path: '/home/{{ ansible_user }}//Investment-Project/src/minio'
        state: directory
        recurse: yes
        mode: "0777"