- hosts: all
  become: yes
  tasks:
    - name: create the 'dongwook' user
      user: name=dongwook.test0 append=yes state=present createhome=yes shell=/bin/bash
 
    - name: allow 'dongwook.test0' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'dongwook.test0 ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'