- name: Run all playbooks in order
  hosts: all

  gather_facts: true

  tasks:
    - name: Run initial.yaml
      include_tasks: initial.yaml

    - name: Run kube-dependencies.yaml
      include_tasks: kube-dependencies.yaml

    - name: Run master.yaml
      include_tasks: master.yaml

    - name: Run workers.yaml
      include_tasks: workers.yaml